version: '3.8'

services:
  # PostgreSQL + PostGIS
  postgres:
    image: postgis/postgis:14-3.3
    container_name: polenavi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: polenavi
      POSTGRES_PASSWORD: polenavi_dev_password
      POSTGRES_DB: polenavi_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polenavi"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin（DB管理ツール）
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: polenavi-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@polenavi.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Redis（セッション管理）
  redis:
    image: redis:7-alpine
    container_name: polenavi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: