// 何を: 電柱登録のビジネスロジック
// なぜ: コントローラーから分離して再利用性を高めるため

import { PrismaClient } from '@prisma/client';
import { ValidationError, NotFoundError } from '../utils/AppError';
import { normalizePoleNumber } from '../utils/normalize';
import { CONSTANTS } from '../config/constants';

const prisma = new PrismaClient();

/**
 * 電柱登録のリクエストデータ
 */
export interface CreatePoleRequest {
  latitude: number;
  longitude: number;
  poleType: 'electric' | 'other';
  poleSubType?: 'light' | 'sign' | 'traffic' | 'other';
  plateCount: number;
  numbers: string[];
  registeredBy?: number;
  registeredByName?: string;
}

/**
 * 電柱を新規登録
 */
export async function createPole(data: CreatePoleRequest) {
  // バリデーション
  validatePoleData(data);

  // 近くの電柱を検索（重複チェック用）
  const nearbyPoles = await findNearbyPoles(data.latitude, data.longitude);

  // トランザクションで登録
  const result = await prisma.$transaction(async (tx: any) => {
    // 1. 電柱を作成
    const pole = await tx.pole.create({
      data: {
        latitude: data.latitude,
        longitude: data.longitude,
        poleTypeName: getPoleTypeName(data.poleType, data.poleSubType),
        numberCount: data.numbers.length,
        photoCount: 0,
      },
    });

    // 2. 番号を登録
    const poleNumbers = await Promise.all(
      data.numbers.map(async (number) => {
        if (!number || number.trim() === '') return null;

        // 番号を正規化
        const normalizedNumber = normalizePoleNumber(number.trim());

        return tx.poleNumber.create({
          data: {
            poleId: pole.id,
            poleNumber: normalizedNumber,
            operatorName: getOperatorName(data.poleType, data.poleSubType),
            isAutoGenerated: normalizedNumber.startsWith('#NoID-'),
            locationMethod: 'auto',
            registeredBy: data.registeredBy,
            registeredByName: data.registeredByName || 'guest',
          },
        });
      })
    );

    // nullを除外
    const createdNumbers = poleNumbers.filter((n) => n !== null);

    return {
      pole,
      numbers: createdNumbers,
      nearbyPoles,
    };
  });

  return result;
}

/**
 * 近くの電柱を検索
 *
 * @param lat 緯度
 * @param lng 経度
 * @param radiusMeters 検索半径（メートル）
 */
export async function findNearbyPoles(
  lat: number,
  lng: number,
  radiusMeters = CONSTANTS.DISTANCE.NEARBY_CHECK
) {
  // TODO: PostGISを使った空間検索を実装
  // 現在は簡易版（緯度経度の差分で判定）

  const latDiff = radiusMeters / 111000; // 1度 ≈ 111km
  const lngDiff = radiusMeters / (111000 * Math.cos((lat * Math.PI) / 180));

  const poles = await prisma.pole.findMany({
    where: {
      latitude: {
        gte: lat - latDiff,
        lte: lat + latDiff,
      },
      longitude: {
        gte: lng - lngDiff,
        lte: lng + lngDiff,
      },
    },
    include: {
      poleNumbers: true,
    },
  });

  // 正確な距離を計算
  return poles
    .map((pole: any) => ({
      ...pole,
      distance: calculateDistance(lat, lng, Number(pole.latitude), Number(pole.longitude)),
    }))
    .filter((pole: any) => pole.distance <= radiusMeters)
    .sort((a: any, b: any) => a.distance - b.distance);
}

/**
 * 電柱IDから詳細情報を取得
 */
export async function getPoleById(poleId: number) {
  const pole = await prisma.pole.findUnique({
    where: { id: poleId },
    include: {
      poleNumbers: true,
      photos: {
        where: {
          deletedAt: null,
        },
      },
      memos: {
        orderBy: {
          createdAt: 'desc',
        },
      },
    },
  });

  if (!pole) {
    throw new NotFoundError('電柱が見つかりません');
  }

  return pole;
}

/**
 * 電柱番号から検索
 */
export async function searchByNumber(number: string) {
  const normalizedNumber = normalizePoleNumber(number);

  const poleNumber = await prisma.poleNumber.findUnique({
    where: { poleNumber: normalizedNumber },
    include: {
      pole: {
        include: {
          poleNumbers: true,
        },
      },
    },
  });

  if (!poleNumber) {
    throw new NotFoundError('番号が見つかりません');
  }

  return poleNumber;
}

// ========================================
// ヘルパー関数
// ========================================

/**
 * 電柱データのバリデーション
 */
function validatePoleData(data: CreatePoleRequest): void {
  // 位置情報のチェック
  if (!data.latitude || !data.longitude) {
    throw new ValidationError('位置情報が必要です');
  }

  if (data.latitude < -90 || data.latitude > 90) {
    throw new ValidationError('緯度が不正です');
  }

  if (data.longitude < -180 || data.longitude > 180) {
    throw new ValidationError('経度が不正です');
  }

  // 柱の種類のチェック
  if (!['electric', 'other'].includes(data.poleType)) {
    throw new ValidationError('柱の種類が不正です');
  }

  // その他の場合はサブタイプが必要
  if (data.poleType === 'other' && !data.poleSubType) {
    throw new ValidationError('柱の詳細を選択してください');
  }

  // 番号札枚数のチェック
  if (data.plateCount === null || data.plateCount === undefined) {
    throw new ValidationError('番号札の枚数を選択してください');
  }

  // 番号のチェック
  if (!data.numbers || data.numbers.length === 0) {
    throw new ValidationError('番号が必要です');
  }
}

/**
 * 柱の種類名を取得
 */
function getPoleTypeName(poleType: string, poleSubType?: string): string {
  if (poleType === 'electric') return '電柱';

  switch (poleSubType) {
    case 'light':
      return '照明柱';
    case 'sign':
      return '標識柱';
    case 'traffic':
      return '信号柱';
    default:
      return 'その他';
  }
}

/**
 * 事業者名を取得
 */
function getOperatorName(poleType: string, poleSubType?: string): string {
  if (poleType === 'electric') return '電力会社';

  switch (poleSubType) {
    case 'light':
      return '自治体';
    case 'sign':
      return '国交省';
    case 'traffic':
      return '警察';
    default:
      return 'その他';
  }
}

/**
 * 2点間の距離を計算（メートル）
 *
 * Haversine formula を使用
 */
function calculateDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371000; // 地球の半径（メートル）
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);

  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c; // メートル
}
