// 何を: 電柱登録のビジネスロジック
// なぜ: コントローラーから分離して再利用性を高めるため

import { PrismaClient } from '@prisma/client';
import { ValidationError, NotFoundError } from '../utils/AppError';
import { normalizePoleNumber } from '../utils/normalize';
import { CONSTANTS } from '../config/constants';

const prisma = new PrismaClient();

/**
 * 電柱登録のリクエストデータ
 */
export interface CreatePoleRequest {
  latitude: number;
  longitude: number;
  poleType: 'electric' | 'other';
  poleSubType?: 'light' | 'sign' | 'traffic' | 'other';
  plateCount: number;
  numbers: string[];
  registeredBy?: number;
  registeredByName?: string;
  memo?: string;
  hashtag?: string | string[]; // 文字列または配列を受け付ける
}

/**
 * 電柱を新規登録
 */
export async function createPole(data: CreatePoleRequest) {
  console.log('🔍 [Service] data.registeredBy:', data.registeredBy);
  console.log('🔍 [Service] data.registeredByName:', data.registeredByName);
  console.log('🔍 [Service] data.memo:', data.memo);
  console.log('🔍 [Service] data.hashtag:', data.hashtag);

  // バリデーション
  validatePoleData(data);

  // 近くの電柱を検索（重複チェック用）
  const nearbyPoles = await findNearbyPoles(data.latitude, data.longitude);

  // トランザクションで登録
  const result = await prisma.$transaction(async (tx: any) => {
    // 1. 電柱を作成
    const pole = await tx.pole.create({
      data: {
        latitude: data.latitude,
        longitude: data.longitude,
        poleTypeName: getPoleTypeName(data.poleType, data.poleSubType),
        numberCount: data.numbers.length > 0 ? data.numbers.length : 1, // 番号なしの場合は自動生成番号1つ
        photoCount: 0,
      },
    });

    // 2. 番号を登録
    let numbersToRegister = data.numbers;

    // 番号が空の場合は自動生成番号を作成
    if (!numbersToRegister || numbersToRegister.length === 0) {
      const autoNumber = generateAutoNumber();
      numbersToRegister = [autoNumber];
    }

    // 空文字列を事前にフィルタリング
    const validNumbers = numbersToRegister.filter(number => number && number.trim() !== '');

    // 正規化した番号のリストを作成
    const normalizedNumbers = validNumbers.map(number => {
      const normalized = normalizePoleNumber(number.trim());
      return normalized === '?' ? `?-pole${pole.id}` : normalized;
    });

    // ✅ 既存の番号をチェック（重複検出）
    const existingNumbers = await tx.poleNumber.findMany({
      where: {
        poleNumber: {
          in: normalizedNumbers,
        },
      },
      select: {
        poleNumber: true,
      },
    });

    if (existingNumbers.length > 0) {
      // 既に登録されている番号を取得
      const duplicateNumber = existingNumbers[0].poleNumber;
      // 元の番号に戻す（表示用）
      const originalNumber = validNumbers.find(
        num => normalizePoleNumber(num.trim()) === duplicateNumber
      ) || duplicateNumber;
      throw new ValidationError(`番号「${originalNumber}」は既に他の電柱で使用されています`);
    }

    // ✅ 同じ番号が複数入力されていないかチェック
    const uniqueCheck = new Set(normalizedNumbers);
    if (uniqueCheck.size !== normalizedNumbers.length) {
      throw new ValidationError('同じ番号が複数入力されています。異なる番号を入力してください');
    }

    const poleNumbers = await Promise.all(
      normalizedNumbers.map(async (normalizedNumber) => {
        return tx.poleNumber.create({
          data: {
            poleId: pole.id,
            poleNumber: normalizedNumber,
            operatorName: getOperatorName(data.poleType, data.poleSubType),
            isAutoGenerated: normalizedNumber.startsWith('#NoID-'),
            locationMethod: 'auto',
            registeredBy: data.registeredBy,
            registeredByName: data.registeredByName || 'guest',
          },
        });
      })
    );

    const createdNumbers = poleNumbers;

    // 3. メモ・ハッシュタグを登録（もしあれば）
    let createdMemo = null;
    if ((data.memo && data.memo.trim()) || (data.hashtag && data.hashtag.length > 0)) {
      // createdByNameを確実に文字列にする
      const createdByName = (data.registeredByName && data.registeredByName.trim()) || 'guest';

      // ハッシュタグを配列に変換（文字列の場合はスペースで分割）
      let hashtagArray: string[] = [];
      if (data.hashtag) {
        if (Array.isArray(data.hashtag)) {
          hashtagArray = data.hashtag;
        } else if (typeof data.hashtag === 'string' && data.hashtag.trim()) {
          // スペースで分割して、空文字列を除外
          hashtagArray = data.hashtag.split(/\s+/).filter(tag => tag.trim().length > 0);
        }
      }

      console.log('🔍 [Service] poleMemo.create() 直前:');
      console.log('  - poleId:', pole.id);
      console.log('  - hashtags:', hashtagArray);
      console.log('  - memoText:', data.memo || null);
      console.log('  - createdBy:', data.registeredBy);
      console.log('  - createdByName:', createdByName);

      createdMemo = await tx.poleMemo.create({
        data: {
          poleId: pole.id,
          hashtags: hashtagArray,
          memoText: data.memo || null,
          createdBy: data.registeredBy,
          createdByName: createdByName,
          isPublic: true,
          visibility: 'public',
          groupId: null,
        },
      });

      console.log('✅ [Service] poleMemo 作成成功');
    }

    return {
      pole,
      numbers: createdNumbers,
      memo: createdMemo,
      nearbyPoles,
    };
  });

  return result;
}

/**
 * 近くの電柱を検索
 *
 * @param lat 緯度
 * @param lng 経度
 * @param radiusMeters 検索半径（メートル）
 */
export async function findNearbyPoles(
  lat: number,
  lng: number,
  radiusMeters = CONSTANTS.DISTANCE.NEARBY_CHECK
) {
  // TODO: PostGISを使った空間検索を実装
  // 現在は簡易版（緯度経度の差分で判定）

  const latDiff = radiusMeters / 111000; // 1度 ≈ 111km
  const lngDiff = radiusMeters / (111000 * Math.cos((lat * Math.PI) / 180));

  const poles = await prisma.pole.findMany({
    where: {
      latitude: {
        gte: lat - latDiff,
        lte: lat + latDiff,
      },
      longitude: {
        gte: lng - lngDiff,
        lte: lng + lngDiff,
      },
    },
    include: {
      poleNumbers: true,
    },
  });

  // 正確な距離を計算
  return poles
    .map((pole: any) => ({
      ...pole,
      distance: calculateDistance(lat, lng, Number(pole.latitude), Number(pole.longitude)),
    }))
    .filter((pole: any) => pole.distance <= radiusMeters)
    .sort((a: any, b: any) => a.distance - b.distance);
}

/**
 * 境界ボックス内の電柱を検索
 *
 * @param minLat 最小緯度（南西の緯度）
 * @param maxLat 最大緯度（北東の緯度）
 * @param minLng 最小経度（南西の経度）
 * @param maxLng 最大経度（北東の経度）
 */
export async function findPolesInBounds(
  minLat: number,
  maxLat: number,
  minLng: number,
  maxLng: number
) {
  console.log(`🗺️ 境界ボックス検索: lat[${minLat}, ${maxLat}], lng[${minLng}, ${maxLng}]`);

  const poles = await prisma.pole.findMany({
    where: {
      latitude: {
        gte: minLat,
        lte: maxLat,
      },
      longitude: {
        gte: minLng,
        lte: maxLng,
      },
    },
    include: {
      poleNumbers: true,
    },
  });

  console.log(`✅ ${poles.length}本の電柱を取得`);

  return poles;
}

/**
 * 電柱IDから詳細情報を取得
 */
export async function getPoleById(poleId: number) {
  try {
    console.log(`🔍 電柱詳細取得開始: poleId=${poleId}`);

    const pole = await prisma.pole.findUnique({
      where: { id: poleId },
      include: {
        poleNumbers: {
          include: {
            user: {
              select: {
                id: true,
                username: true,
                displayName: true,
                showUsername: true,
              },
            },
          },
        },
        photos: {
          where: {
            deletedAt: null,
          },
          include: {
            uploadedByUser: {
              select: {
                id: true,
                username: true,
                displayName: true,
                showUsername: true,
              },
            },
          },
        },
        memos: {
          orderBy: {
            createdAt: 'desc',
          },
          include: {
            createdByUser: {
              select: {
                id: true,
                username: true,
                displayName: true,
                showUsername: true,
              },
            },
          },
        },
      },
    });

    if (!pole) {
      console.log(`❌ 電柱が見つかりません: poleId=${poleId}`);
      throw new NotFoundError('電柱が見つかりません');
    }

    console.log(`✅ 電柱データ取得成功: poleId=${poleId}, numbers=${pole.poleNumbers?.length || 0}`);

    // 最初の番号の登録者を電柱の登録者として扱う
    const firstNumber = pole.poleNumbers?.[0];
    const createdBy = firstNumber?.user;

    // showUsernameがfalseの場合は匿名にする
    let registeredByName = '匿名';
    if (createdBy) {
      if (createdBy.showUsername) {
        registeredByName = createdBy.displayName || createdBy.username || '匿名';
      }
    }

    console.log(`📝 登録者名: ${registeredByName}`);

    return {
      ...pole,
      registeredByName,
    };
  } catch (error) {
    console.error(`❌ getPoleById エラー:`, error);
    throw error;
  }
}

/**
 * 電柱番号から検索
 */
export async function searchByNumber(number: string) {
  const normalizedNumber = normalizePoleNumber(number);

  const poleNumber = await prisma.poleNumber.findUnique({
    where: { poleNumber: normalizedNumber },
    include: {
      pole: {
        include: {
          poleNumbers: true,
        },
      },
    },
  });

  if (!poleNumber) {
    throw new NotFoundError('番号が見つかりません');
  }

  return poleNumber;
}

// ========================================
// ヘルパー関数
// ========================================

/**
 * 電柱データのバリデーション
 */
function validatePoleData(data: CreatePoleRequest): void {
  // 位置情報のチェック
  if (!data.latitude || !data.longitude) {
    throw new ValidationError('位置情報が必要です');
  }

  if (data.latitude < -90 || data.latitude > 90) {
    throw new ValidationError('緯度が不正です');
  }

  if (data.longitude < -180 || data.longitude > 180) {
    throw new ValidationError('経度が不正です');
  }

  // 柱の種類のチェック
  if (!['electric', 'other'].includes(data.poleType)) {
    throw new ValidationError('柱の種類が不正です');
  }

  // その他の場合はサブタイプが必要
  if (data.poleType === 'other' && !data.poleSubType) {
    throw new ValidationError('柱の詳細を選択してください');
  }

  // 番号札枚数のチェック
  if (data.plateCount === null || data.plateCount === undefined) {
    throw new ValidationError('番号札の枚数を選択してください');
  }

  // 番号のチェック（番号札が0枚の場合は不要）
  if (data.plateCount > 0 && (!data.numbers || data.numbers.length === 0)) {
    throw new ValidationError('番号が必要です');
  }
}

/**
 * 自動生成番号を作成
 */
function generateAutoNumber(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let randomStr = '';
  for (let i = 0; i < 8; i++) {
    const randomIndex = Math.floor(Math.random() * chars.length);
    randomStr += chars[randomIndex];
  }
  return `#NoID-${randomStr}`;
}

/**
 * 柱の種類名を取得
 */
function getPoleTypeName(poleType: string, poleSubType?: string): string {
  if (poleType === 'electric') return '電柱';

  switch (poleSubType) {
    case 'light':
      return '照明柱';
    case 'sign':
      return '標識柱';
    case 'traffic':
      return '信号柱';
    default:
      return 'その他';
  }
}

/**
 * 事業者名を取得
 */
function getOperatorName(poleType: string, poleSubType?: string): string {
  if (poleType === 'electric') return '電力会社';

  switch (poleSubType) {
    case 'light':
      return '自治体';
    case 'sign':
      return '国交省';
    case 'traffic':
      return '警察';
    default:
      return 'その他';
  }
}

/**
 * 2点間の距離を計算（メートル）
 *
 * Haversine formula を使用
 */
function calculateDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371000; // 地球の半径（メートル）
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);

  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c; // メートル
}

/**
 * メモ・ハッシュタグで電柱を検索
 */
export async function searchPolesByMemo(searchQuery: string) {
  if (!searchQuery || searchQuery.trim().length === 0) {
    throw new ValidationError('検索キーワードを入力してください');
  }

  const trimmedQuery = searchQuery.trim();

  // 複数のハッシュタグが含まれている場合はスペースで分割
  let keywords = trimmedQuery.split(/\s+/).filter(k => k.length > 0);

  // キーワードに#が付いていない場合は自動で付ける（ハッシュタグ検索用）
  // ただし、元のキーワードも検索対象に含める（メモテキスト検索用）
  const keywordsWithHash = keywords.map(k => k.startsWith('#') ? k : `#${k}`);
  const allKeywords = [...new Set([...keywords, ...keywordsWithHash])]; // 重複除去

  console.log('🔍 [searchPolesByMemo] 検索開始');
  console.log('  - 元のクエリ:', searchQuery);
  console.log('  - キーワード:', keywords);
  console.log('  - ハッシュタグ付きキーワード:', allKeywords);

  // デバッグ: 全メモを確認
  const allPublicMemos = await prisma.poleMemo.findMany({
    where: { isPublic: true },
    select: {
      id: true,
      hashtags: true,
      memoText: true,
    },
    take: 10,
  });
  console.log('  - 全メモ（最初の10件）:');
  allPublicMemos.forEach(m => {
    console.log(`    ID:${m.id}, ハッシュタグ:`, m.hashtags, `, メモ:${m.memoText?.substring(0, 20)}`);
  });

  // 各キーワードごとに検索を実行し、結果をマージ
  const allMemos: any[] = [];
  const seenIds = new Set<number>();

  for (const keyword of allKeywords) {
    try {
      console.log(`  - キーワード "${keyword}" で検索中...`);

      // 完全一致検索（配列内）
      const exactMemos = await prisma.poleMemo.findMany({
        where: {
          isPublic: true,
          hashtags: {
            has: keyword,
          },
        },
        include: {
          pole: {
            include: {
              poleNumbers: true,
            },
          },
        },
        take: 50,
      });
      console.log(`    - 完全一致: ${exactMemos.length}件`);

      // メモテキストでの部分一致検索
      const textMemos = await prisma.poleMemo.findMany({
        where: {
          isPublic: true,
          memoText: {
            contains: keyword,
            mode: 'insensitive',
          },
        },
        include: {
          pole: {
            include: {
              poleNumbers: true,
            },
          },
        },
        take: 50,
      });
      console.log(`    - メモテキスト: ${textMemos.length}件`);

      // ハッシュタグ配列を文字列に変換して部分一致検索（生SQL）
      const partialMemos = await prisma.$queryRaw<any[]>`
        SELECT
          pm.*,
          json_build_object(
            'id', p.id,
            'latitude', p.latitude,
            'longitude', p.longitude,
            'poleTypeName', p.pole_type_name,
            'numberCount', p.number_count
          ) as pole
        FROM pole_memos pm
        JOIN poles p ON pm.pole_id = p.id
        WHERE pm.is_public = true
        AND array_to_string(pm.hashtags, ' ') ILIKE ${`%${keyword}%`}
        LIMIT 50
      `;
      console.log(`    - 部分一致: ${partialMemos.length}件`);

      // 結果をマージ（重複排除）
      [...exactMemos, ...textMemos, ...partialMemos].forEach((memo: any) => {
        if (!seenIds.has(memo.id)) {
          seenIds.add(memo.id);
          allMemos.push(memo);
        }
      });
    } catch (error) {
      console.error(`キーワード "${keyword}" の検索エラー:`, error);
    }
  }

  const memos = allMemos.slice(0, 50); // 最大50件に制限

  console.log('  - 検索結果:', memos.length, '件');
  if (memos.length > 0) {
    console.log('  - 最初の結果のハッシュタグ:', memos[0].hashtags);
  }

  // 重複する電柱を排除
  const uniquePoles = Array.from(
    new Map(memos.map((memo: any) => [memo.pole?.id || memo.poleId, memo])).values()
  );

  console.log('  - ユニーク電柱数:', uniquePoles.length);

  return uniquePoles.map((memo: any) => {
    // Prismaの結果の場合
    if (memo.pole && memo.pole.poleNumbers) {
      return {
        poleId: memo.pole.id,
        latitude: memo.pole.latitude,
        longitude: memo.pole.longitude,
        poleTypeName: memo.pole.poleTypeName,
        numberCount: memo.pole.numberCount,
        numbers: memo.pole.poleNumbers.map((pn: any) => pn.poleNumber),
        memoText: memo.memoText,
        hashtags: memo.hashtags,
        createdByName: memo.createdByName,
        createdAt: memo.createdAt,
      };
    }
    // 生SQLの結果の場合
    else {
      return {
        poleId: memo.poleId,
        latitude: Number(memo.pole?.latitude || memo.latitude),
        longitude: Number(memo.pole?.longitude || memo.longitude),
        poleTypeName: memo.pole?.poleTypeName || memo.poleTypeName,
        numberCount: memo.pole?.numberCount || memo.numberCount,
        numbers: [], // 生SQLの場合は後で番号を取得
        memoText: memo.memoText,
        hashtags: memo.hashtags,
        createdByName: memo.createdByName,
        createdAt: memo.createdAt,
      };
    }
  });
}

/**
 * 電柱番号を追加
 */
export async function addPoleNumber(poleId: number, poleNumber: string) {
  // 電柱の存在確認
  const pole = await prisma.pole.findUnique({
    where: { id: poleId },
  });

  if (!pole) {
    throw new NotFoundError('指定された電柱が見つかりません');
  }

  // 番号の正規化
  const normalized = normalizePoleNumber(poleNumber);

  // 重複チェック
  const existing = await prisma.poleNumber.findFirst({
    where: {
      poleId,
      poleNumber: normalized,
    },
  });

  if (existing) {
    throw new ValidationError('この番号は既に登録されています');
  }

  // 番号を追加
  const result = await prisma.$transaction(async (tx: any) => {
    const newNumber = await tx.poleNumber.create({
      data: {
        poleId,
        poleNumber: normalized,
        registeredBy: null, // TODO: ログイン機能実装後にユーザーIDを設定
        registeredByName: 'ゲストユーザー',
      },
    });

    // 電柱のnumberCountを更新
    await tx.pole.update({
      where: { id: poleId },
      data: {
        numberCount: {
          increment: 1,
        },
      },
    });

    return newNumber;
  });

  return {
    id: result.id,
    poleNumber: result.poleNumber,
  };
}

/**
 * 電柱の位置を修正
 */
export async function updatePoleLocation(poleId: number, latitude: number, longitude: number) {
  // 電柱の存在確認
  const pole = await prisma.pole.findUnique({
    where: { id: poleId },
  });

  if (!pole) {
    throw new NotFoundError('指定された電柱が見つかりません');
  }

  // 位置を更新
  const updated = await prisma.pole.update({
    where: { id: poleId },
    data: {
      latitude,
      longitude,
    },
  });

  return {
    id: updated.id,
    latitude: updated.latitude,
    longitude: updated.longitude,
  };
}

/**
 * ハッシュタグで電柱を検索
 */
export async function getPolesByHashtag(tag: string, userId?: number) {
  // タグに#を付ける（フロントエンドから#なしで来るため）
  const hashtagWithHash = tag.startsWith('#') ? tag : `#${tag}`;

  const poles = await prisma.pole.findMany({
    where: {
      memos: {
        some: {
          hashtags: {
            has: hashtagWithHash,
          },
          ...(userId && { createdBy: userId }),
        },
      },
    },
    include: {
      memos: {
        where: {
          hashtags: {
            has: hashtagWithHash,
          },
          ...(userId && { createdBy: userId }),
        },
        select: {
          id: true,
          memoText: true,
          hashtags: true,
          createdAt: true,
          createdByUser: {
            select: {
              id: true,
              username: true,
              displayName: true,
            },
          },
        },
      },
      photos: {
        select: {
          id: true,
          photoUrl: true,
        },
        take: 1,
      },
    },
    orderBy: {
      createdAt: 'desc',
    },
  });

  return poles;
}
